config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  mount Weathers::WeathersApi => '/'

  # get '/my_page', to: 'pages#index'
  resources :pages
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  # sanitizes :title, on: :create
end

app/models/weather.rb
# frozen_string_literal: true

class Weather < ApplicationRecord
  def self.current_weather
    request = 'SELECT * FROM weathers ORDER BY id DESC LIMIT 1'
    result =
      Rails.cache.fetch('current', expires_in: 1.minute) do
        last
      end
    prepared_data(result)
  end

  def self.last_weathers
    request = 'SELECT * FROM weathers ORDER BY id DESC LIMIT 24'
    result =
      Rails.cache.fetch('last24', expires_in: 1.minute) do
        ActiveRecord::Base.connection.exec_query(request)[0]
      end
    prepared_data(result)
  end

  def self.max
    request = 'SELECT * FROM (SELECT * FROM weathers ORDER BY id DESC LIMIT 24) AS t1 ORDER BY temperature DESC LIMIT 1'
    result =
      Rails.cache.fetch('max', expires_in: 1.minute) do
        ActiveRecord::Base.connection.exec_query(request)[0]
      end
    prepared_data(result)
  end

  def self.min
    request = 'SELECT * FROM (SELECT * FROM weathers ORDER BY id DESC LIMIT 24) AS t1 ORDER BY temperature ASC LIMIT 1'
    result =
      Rails.cache.fetch('min', expires_in: 1.minute) do
        ActiveRecord::Base.connection.exec_query(request)[0]
      end
    prepared_data(result)
  end

  def self.avg
    request = 'SELECT AVG(temperature) AS temperature FROM (SELECT * FROM weathers ORDER BY id DESC LIMIT 24) AS t1'
    Rails.cache.fetch('avg', expires_in: 1.minute) do
      ActiveRecord::Base.connection.exec_query(request)[0]['temperature'].round(1)
    end
  end

  def self.by_time(unix_time)
    return { message: '400: Blank time', status: 400 } if unix_time.nil?

    TempByTimeService.new(unix_time).result
  end

  def self.prepared_data(weather)
    {
      time: weather['local_time'],
      temperature: weather['temperature']
    }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# require 'sanitize'

class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    Page.find_by(id: params[:id])
  end

  def create
    # sanitize_params = Sanitize.fragment(params[:title])
    # sanitize_params = params[:title]
    Page.create user_id: params[:user_id], article_id: params[:article_id], text: params[:text]
    redirect_to action: "index"
  end

  def destroy
    Page.find_by(id: params[:id]).destroy
    redirect_to action: "index"
  end
end

app/controllers/weathers_controller.rb
# frozen_string_literal: true

class WeathersController < ApplicationController
  def current
    render json: Weather.current_weather
    #for rebase
  end

  def historical
    render json: Weather.last_weathers
  end

  def historical_max
    render json: Weather.max
  end

  def historical_min
    render json: Weather.min
  end

  def historical_avg
    render json: Weather.avg
  end

  def by_time
    render json: Weather.by_time(params[:unix_time])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeatherApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Hello</h1>

<%= form_with url: pages_path, method: :post do |form| %>
    <%= form.label :user_id, 'user_id: ' %>
    <%= form.text_field :user_id %>

    <%= form.label :article_id, 'article_id: ' %>
    <%= form.text_field :article_id %>

    <%= form.label :text, 'text: ' %>
    <%= form.text_field :text %>

    <%= form.submit "Create" %>
<% end %>

<table border=1 cellspacing=0 style="width: 60%;">
  <tr>
    <th>id</th>
    <th>user_id</th>
    <th>article_id</th>
    <th>text</th>
  </tr>
  <% @pages.each do |page| %>
      <tr>
        <td> <%= page.id %> </td>
        <td> <%= page.user_id %> </td>
        <td> <%= page.article_id %> </td>
        <td> <%= page.text %> </td>
        <td> <%= button_to 'Delete', page_path(page.id), method: :delete, data: { confirm: true } %> </td>
      </tr>
  <% end %>
</table>